services:
  database:
    image: neo4j:latest
    ports:
      - "7474:7474" # Interfaz HTTP (Browser)
      - "7687:7687" # Protocolo Bolt para Python
    environment:
      - NEO4J_AUTH=neo4j/password123
      # 1. Cargar plugins oficiales
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
      # 2. Desbloquear procedimientos (incluido el tuyo)
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*,ontology.util.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,n10s.*,ontology.util.*
      # Configuración específica para cargar n10s como extensión unmanaged
      # - NEO4J_dbms_unmanaged_extension_classes=n10s.endpoint=/rdf
      # 3. Configuración específica para APOC
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
    volumes:
      - neo4j_data:/data
      - ./backend/import:/import # Mapea tu carpeta local de archivos para importar
      # 4. Mapear tu JAR personalizado a la carpeta de plugins de Neo4j
      - ./backend/plugins/Neo4jOntologyLibrary-1.28-JSS.jar:/plugins/Neo4jOntologyLibrary-1.28-JSS.jar
      - ./backend/plugins/neosemantics-5.26.0.jar:/plugins/neosemantics-5.26.0.jar
      
      
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env  
    environment:
      - NEO4J_URI=bolt://database:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - PYTHONUNBUFFERED=1  # Permite ver los logs en tiempo real
    volumes:
      - ./backend:/app      # Mapea tu código local al WORKDIR del contenedor
    # Ejemplo si usas FastAPI con Uvicorn:
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app           # Sincroniza tu carpeta local con la del contenedor
      - /app/node_modules         # Evita que se sobrescriban las librerías del contenedor
    depends_on:
      - backend

volumes:
  neo4j_data:
